from __future__ import annotations

import html

import pandas as pd
import streamlit as st

from analysis.intelligence import assessment, detect_risks, trend_summary
from analysis.timeline import timeline_summary
from analysis.scorecard import build_scorecard
from analysis.resilience import build_resilience_intelligence, simulate_scenario
from components.cards import metric_card, status_badge
from components.cinematic import render_health_orb, render_spotlight, render_telemetry_strip
from components.charts import render_health_radar, render_history_chart, render_health_trajectory, render_repository_health_timeline
from components.ui import empty_state, health_dimension, insight_card, page_header, section_header
from data.history import get_snapshots


def _fmt(value: int | float) -> str:
    value = value or 0
    if value >= 1_000_000:
        return f"{value / 1_000_000:.1f}M"
    if value >= 1_000:
        return f"{value / 1_000:.1f}K"
    return f"{value:,}"


def _delta(current, previous, inverse=False):
    if previous is None or previous == 0:
        return None
    change = ((current - previous) / abs(previous)) * 100
    good = change <= 0 if inverse else change >= 0
    sign = "+" if change > 0 else ""
    return f"{sign}{change:.1f}%", "good" if good else "bad"


def _health_status(score: float):
    if score >= 80:
        return "HEALTHY", "good"
    if score >= 60:
        return "MODERATE", "warning"
    return "AT RISK", "danger"


def _history_frame(repo_name: str) -> pd.DataFrame:
    snapshots = list(reversed(get_snapshots(repo_name, limit=30)))
    return pd.DataFrame(snapshots) if snapshots else pd.DataFrame()


def _current_snapshot(analysis) -> dict:
    metrics = analysis.metrics or {}
    return {
        "stars": analysis.repository.stars,
        "forks": analysis.repository.forks,
        "issues": metrics.get("open_issue_count", 0),
        "pull_requests": metrics.get("open_pull_request_count", 0),
        "contributors": metrics.get("total_contributors", 0),
        "commits": metrics.get("recent_commit_count", 0),
        "health": metrics.get("repository_health_score", 0),
    }


def _render_what_changed(analysis, previous):
    section_header("What changed", "The strongest movements since the previous stored snapshot.", "Delta intelligence")
    if not previous:
        st.info("This is the first comparison point. Re-scan the repository later to unlock change intelligence.")
        return
    trends = trend_summary(_current_snapshot(analysis), previous)
    changed = [t for t in trends if t["change"] != 0]
    if not changed:
        st.success("No measured metrics changed since the previous scan.")
        return
    for t in changed:
        symbol = "↑" if t["direction"] == "up" else "↓"
        cls = "positive" if t["interpretation"] == "improved" else "negative"
        pct = f"{t['pct']:+.1f}%" if t["pct"] is not None else "new"
        st.html(
            f'<div class="change-row"><span class="change-symbol {cls}">{symbol}</span><strong>{html.escape(t["label"])}</strong><span>{t["previous"]:,.1f} → {t["current"]:,.1f} · {pct}</span></div>'
        )


def _render_history(repo_name: str):
    df = _history_frame(repo_name)
    if df.empty:
        st.info("No persistent history yet. Analyze this repository again later to build trends.")
        return

    section_header("Live history", "Every analysis creates a timestamped snapshot that feeds the trend layer.", "Historical telemetry")
    chart_df = df.copy()
    chart_df["captured_at"] = pd.to_datetime(chart_df["captured_at"], errors="coerce")
    metric_options = {
        "Health score": "health_score",
        "Recent commits": "recent_commits",
        "Open issues": "open_issues",
        "Open pull requests": "open_pull_requests",
        "Contributors": "contributors",
        "Stars": "stars",
        "Forks": "forks",
        "Engineering": "engineering_score",
    }
    selected = st.selectbox("Historical metric", list(metric_options), key="phase2_history_metric", label_visibility="collapsed")
    render_history_chart(chart_df, metric_options[selected], selected, height=340)
    st.caption("Hover points to inspect individual snapshots. The chart uses the persistent SQLite history generated by previous repository scans.")


def _render_scorecard(analysis, history_df: pd.DataFrame, risks, assessment_result):
    """Render the executive 10-second repository scorecard."""
    scorecard = build_scorecard(analysis.metrics or {}, history_df.to_dict("records") if not history_df.empty else [])
    section_header("Repository scorecard", "The fastest read on how the repository is doing right now.", "Executive signal")

    cards = scorecard["cards"]
    labels = ["Health", "Activity", "Community", "Stability", "Momentum"]
    cols = st.columns(5)
    for col, label in zip(cols, labels):
        with col:
            tone = scorecard["tones"][label]
            st.html(
                f'<div class="scorecard-metric {tone}">'
                f'<div class="scorecard-metric-label">{html.escape(label)}</div>'
                f'<div class="scorecard-metric-value">{cards[label]:.0f}<span>/100</span></div>'
                f'<div class="scorecard-track"><span style="width:{cards[label]:.1f}%"></span></div>'
                f'</div>'
            )

    strongest = scorecard["strongest_dimension"]
    weakest = scorecard["weakest_dimension"]
    risk_count = len(risks or [])
    primary_action = (assessment_result.get("priorities") or [None])[0] if assessment_result else None
    if not primary_action:
        primary_action = f"Focus on improving {weakest.lower()} to strengthen the repository's next score."

    left, right = st.columns([1.05, 1], vertical_alignment="top")
    with left:
        st.html(
            f'<div class="scorecard-status {scorecard["tone"]}">'
            f'<div class="scorecard-status-kicker">Current state</div>'
            f'<div class="scorecard-status-title">{html.escape(scorecard["status"])}</div>'
            f'<div class="scorecard-status-copy">Strongest signal: <strong>{html.escape(str(strongest))}</strong>. '
            f'Weakest signal: <strong>{html.escape(weakest)}</strong>.</div>'
            f'</div>'
        )
    with right:
        st.html(
            f'<div class="scorecard-action">'
            f'<div class="scorecard-action-kicker">Next best action</div>'
            f'<div class="scorecard-action-title">{html.escape(str(primary_action))}</div>'
            f'<div class="scorecard-action-copy">{risk_count} active risk signal{"s" if risk_count != 1 else ""} · {html.escape(scorecard["momentum_note"])}</div>'
            f'</div>'
        )


def _render_resilience(analysis, history_df: pd.DataFrame):
    """Render the resilience layer with the same glass/card language as the scorecard."""
    snapshots = history_df.to_dict("records") if not history_df.empty else []
    intelligence = build_resilience_intelligence(analysis.metrics or {}, snapshots)
    section_header(
        "Resilience intelligence",
        "Separates present health from the repository's ability to absorb disruption.",
        "Decision intelligence",
    )

    state = intelligence["state"]
    state_tone = (
        "good" if state in {"GROWING", "ACCELERATING", "RECOVERING", "STABLE"}
        else "warning" if state == "MAINTAINER DEPENDENT" else "danger"
    )
    state_icon = {
        "GROWING": "↗", "ACCELERATING": "↗", "RECOVERING": "↺",
        "STABLE": "→", "MAINTAINER DEPENDENT": "◐",
        "UNDER PRESSURE": "!", "DORMANT": "·",
    }.get(state, "•")

    c1, c2, c3 = st.columns([1.18, 0.91, 0.91], vertical_alignment="top")
    with c1:
        st.html(
            f"""<div class=\"resilience-card resilience-state-card {state_tone}\">
                <div class=\"resilience-card-top\"><span class=\"resilience-kicker\">Repository state</span><span class=\"resilience-state-icon\">{state_icon}</span></div>
                <div class=\"resilience-state\">{html.escape(state)}</div>
                <div class=\"resilience-copy\">{html.escape(intelligence["state_reason"])}</div>
            </div>"""
        )
    with c2:
        st.html(
            f"""<div class=\"resilience-card resilience-score-card\">
                <div class=\"resilience-kicker\">Current health</div>
                <div class=\"resilience-score-row\"><div class=\"resilience-score\">{intelligence["health"]:.0f}<span>/100</span></div><span class=\"resilience-score-status\">Operating</span></div>
                <div class=\"resilience-track\"><span style=\"width:{intelligence["health"]:.1f}%\"></span></div>
                <div class=\"resilience-copy\">Present operating condition</div>
            </div>"""
        )
    with c3:
        resilience_tone = "good" if intelligence["resilience"] >= 70 else "warning" if intelligence["resilience"] >= 50 else "danger"
        st.html(
            f"""<div class=\"resilience-card resilience-score-card {resilience_tone}\">
                <div class=\"resilience-kicker\">Resilience</div>
                <div class=\"resilience-score-row\"><div class=\"resilience-score\">{intelligence["resilience"]:.0f}<span>/100</span></div><span class=\"resilience-score-status\">Shock capacity</span></div>
                <div class=\"resilience-track\"><span style=\"width:{intelligence["resilience"]:.1f}%\"></span></div>
                <div class=\"resilience-copy\">Ability to absorb contributor, activity and pressure shocks</div>
            </div>"""
        )

    left, right = st.columns([1.06, 0.94], vertical_alignment="top")
    with left:
        st.markdown('<div class="resilience-subhead"><span>Resilience drivers</span><small>What is shaping the score</small></div>', unsafe_allow_html=True)
        for factor in intelligence["factors"]:
            tone = "good" if factor["score"] >= 75 else "warning" if factor["score"] >= 50 else "danger"
            st.html(
                f"""<div class=\"resilience-factor {tone}\">
                    <div class=\"resilience-factor-top\"><div><strong>{html.escape(factor["name"])}</strong><span>{html.escape(factor["detail"])}</span></div><b>{factor["score"]:.0f}</b></div>
                    <div class=\"resilience-track\"><span style=\"width:{factor["score"]:.1f}%\"></span></div>
                </div>"""
            )

    with right:
        recommendation = intelligence["recommendation"]
        st.html(
            f"""<div class=\"resilience-action\">
                <div class=\"resilience-action-head\"><span class=\"resilience-kicker\">Recommended intervention</span><span class=\"resilience-action-icon\">↗</span></div>
                <div class=\"resilience-action-title\">{html.escape(recommendation["title"])}</div>
                <div class=\"resilience-copy\">{html.escape(recommendation["detail"])}</div>
            </div>"""
        )
        st.markdown('<div class="resilience-subhead scenario-subhead"><span>Scenario lab</span><small>Directional, not predictive</small></div>', unsafe_allow_html=True)
        scenario_labels = {
            "maintainer_inactive": "Primary maintainer unavailable",
            "issue_pressure": "Issue backlog +25%",
            "broaden_ownership": "Ownership broadens",
        }
        selected = st.selectbox("Scenario", list(scenario_labels), format_func=lambda x: scenario_labels[x], key="resilience_scenario", label_visibility="collapsed")
        scenario = simulate_scenario(analysis.metrics or {}, selected)
        direction = "↑" if scenario["direction"] == "positive" else "↓"
        cls = "positive" if scenario["direction"] == "positive" else "negative"
        st.html(
            f"""<div class=\"scenario-card {cls}\">
                <div class=\"scenario-card-top\"><span class=\"scenario-direction\">{direction}</span><div><div class=\"scenario-title\">{html.escape(scenario["label"])}</div><div class=\"scenario-detail\">{html.escape(scenario["detail"])}</div></div></div>
                <div class=\"scenario-grid\"><div><span>Health</span><strong>{scenario["base_health"]:.0f}<i>→</i>{scenario["projected_health"]:.0f}</strong></div><div><span>Resilience</span><strong>{scenario["base_resilience"]:.0f}<i>→</i>{scenario["projected_resilience"]:.0f}</strong></div><div><span>Projected posture</span><strong>{html.escape(scenario["projected_state"])}</strong></div></div>
            </div>"""
        )
        st.caption("Scenario outputs are directional heuristics based on observed RepoPulse signals, not exact forecasts.")


def _render_repo_hero(repo, score: float, status: str, tone: str, previous: dict):
    delta = score - float(previous.get("health", score)) if previous else 0
    delta_text = f"{delta:+.1f} pts since last scan" if previous else "Baseline scan"
    branch = repo.default_branch or "main"
    language = repo.language or "Language not detected"
    description = repo.description or "No repository description provided."
    safe_name = html.escape(repo.full_name)
    safe_description = html.escape(description)
    safe_branch = html.escape(branch)
    safe_language = html.escape(language)
    github_url = f"https://github.com/{repo.full_name}"
    st.html(
        f"""
        <div class="repo-hero">
            <div class="repo-hero-glow"></div>
            <div class="repo-hero-main">
                <div class="repo-kicker">Active repository</div>
                <div class="repo-name">{safe_name}</div>
                <div class="repo-description">{safe_description}</div>
                <div class="repo-meta">
                    <span class="hero-meta-pill">◉ {safe_language}</span>
                    <span class="hero-meta-pill">⌘ {safe_branch}</span>
                    <span class="hero-meta-pill">GitHub telemetry</span>
                </div>
            </div>
            <div class="repo-hero-side">
                <div class="repo-health-label">Repository health</div>
                <div class="repo-health-score">{score:.1f}<span>/100</span></div>
                <span class="status-badge {tone}"><span class="status-dot"></span>{status}</span>
                <div class="repo-health-delta">{html.escape(delta_text)}</div>
                <a class="repo-link" href="{html.escape(github_url)}" target="_blank" rel="noopener noreferrer">Open on GitHub ↗</a>
            </div>
        </div>
        """
    )


def _render_timeline_moments(df: pd.DataFrame):
    """Render explainable repository milestones from persisted snapshots."""
    snapshots = df.to_dict("records") if not df.empty else []
    summary = timeline_summary(snapshots)

    if summary["status"] == "insufficient":
        st.caption(summary["headline"])
        return

    st.html(
        f'<div class="timeline-summary"><span class="timeline-summary-kicker">Repository story</span>'
        f'<strong>{html.escape(summary["headline"])}</strong>'
        f'<span>{summary["snapshot_count"]} stored scans · {len(summary["events"])} meaningful milestones detected</span></div>'
    )

    events = summary["events"]
    if not events:
        st.caption("No major shifts crossed the milestone thresholds. The repository has remained comparatively stable.")
        return

    st.markdown('<div class="timeline-moments">', unsafe_allow_html=True)
    for event in events[:6]:
        try:
            date_value = pd.to_datetime(event["date"], errors="coerce")
            date_text = date_value.strftime("%d %b %Y") if pd.notna(date_value) else "Stored scan"
        except Exception:
            date_text = "Stored scan"
        severity = event.get("severity", "info")
        icon = "↑" if severity == "positive" else "↓" if severity == "negative" else "•"
        card = (
            f'<div class="timeline-moment {html.escape(severity)}">'
            f'<div class="timeline-moment-dot">{icon}</div>'
            f'<div class="timeline-moment-body">'
            f'<div class="timeline-moment-meta">{html.escape(date_text)} · Health {float(event.get("health", 0)):.1f}</div>'
            f'<strong>{html.escape(event["title"])}</strong>'
            f'<span>{html.escape(event["detail"])}</span>'
            f'</div></div>'
        )
        st.html(card)
    st.markdown('</div>', unsafe_allow_html=True)


def dashboard_page():
    analysis = st.session_state.get("repo_analysis")
    if analysis is None:
        page_header("Workspace", "Repository intelligence", "Connect a GitHub repository to turn raw activity into a clear health and risk picture.")
        empty_state("Your command center is waiting", "Analyze a repository from the Repository page. Once data is loaded, this view becomes your live health, trend and risk workspace.", "◈")
        return

    repo = analysis.repository
    metrics = analysis.metrics or {}
    previous = st.session_state.get("previous_snapshot") or {}
    score = float(metrics.get("repository_health_score", 0) or 0)
    status, tone = _health_status(score)
    result = assessment(metrics, previous)
    risks = detect_risks(metrics)

    page_header("Live repository", "Repository command center", f"{repo.full_name} · scanned from GitHub telemetry")
    _render_repo_hero(repo, score, status, tone, previous)

    delta_score = score - float(previous.get("health", score)) if previous else None
    risk_count = len(risks)
    render_telemetry_strip([
        ("Health", f"{score:.1f}", tone),
        ("Risk signals", str(risk_count), "danger" if risk_count >= 3 else "warning" if risk_count else "good"),
        ("Session scans", f"{st.session_state.get('repo_session_count', 0)}/10", "neutral"),
        ("Telemetry", "LIVE", "good"),
    ])

    orb_col, spotlight_col = st.columns([.85, 1.15])
    with orb_col:
        render_health_orb(score, status, delta_score)
    with spotlight_col:
        spotlight_tone = "danger" if any(r.severity in {"Critical", "High"} for r in risks) else "warning" if risks else "good"
        render_spotlight(
            result["weakest_dimension"],
            result["intro"],
            f"{risk_count} risk signal{'s' if risk_count != 1 else ''} detected · {result['priorities'][0] if result['priorities'] else 'No priority action required.'}",
            spotlight_tone,
            "Current intelligence spotlight",
        )

    cards = [
        ("Stars", _fmt(repo.stars), _delta(repo.stars, previous.get("stars")), "GitHub popularity", "★"),
        ("Forks", _fmt(repo.forks), _delta(repo.forks, previous.get("forks")), "Repository copies", "⑂"),
        ("Open issues", _fmt(metrics.get("open_issue_count", 0)), _delta(metrics.get("open_issue_count", 0), previous.get("issues"), True), "Lower backlog is healthier", "!"),
        ("Open PRs", _fmt(metrics.get("open_pull_request_count", 0)), _delta(metrics.get("open_pull_request_count", 0), previous.get("pull_requests"), True), "Lower backlog is healthier", "↗"),
    ]
    cols = st.columns(4)
    for col, (title, value, delta, help_text, icon) in zip(cols, cards):
        with col:
            metric_card(title, value, delta[0] if delta else None, help_text, delta[1] if delta else "neutral", icon=icon)

    section_header("Repository pulse", "The six dimensions behind the current health signal.", "Command center")
    pulse_left, pulse_right = st.columns([1.2, 1])
    with pulse_left:
        dimensions = metrics.get("health_dimensions", {}) or {}
        if dimensions:
            render_health_radar(dimensions, height=300)
            for name, dimension_score in dimensions.items():
                health_dimension(str(name), float(dimension_score or 0))
        else:
            st.info("No health dimension data is available for this scan.")
    with pulse_right:
        if risks:
            for risk in risks[:3]:
                risk_cls = "danger" if risk.severity in {"Critical", "High"} else "warning"
                st.html(
                    f'<div class="mini-risk {risk_cls}"><span class="mini-risk-dot"></span><div><strong>{html.escape(risk.title)}</strong><span>{html.escape(risk.severity)}</span></div></div>'
                )
        else:
            st.success("No major risk signals detected from the current metrics.")

    _render_what_changed(analysis, previous)

    activity = metrics.get("activity_intelligence", {}) or {}
    engineering = metrics.get("engineering_intelligence", {}) or {}
    section_header("Engineering & activity pulse", "Recent development behaviour and engineering hygiene.", "Operational signal")
    p1, p2, p3, p4 = st.columns(4)
    with p1:
        metric_card("Activity", activity.get("status", "Unknown"), f"{activity.get('commit_trend_pct', 0):+.1f}% trend", "Recent commit direction", "good" if activity.get("commit_trend_pct", 0) >= 0 else "bad", "↗")
    with p2:
        engineering_score = float(engineering.get("engineering_score", 0) or 0)
        metric_card("Engineering", f"{engineering_score:.1f}", "Engineering hygiene", "Composite engineering score", "good" if engineering_score >= 80 else "bad", "⌘", progress=engineering_score)
    with p3:
        testing_score = float(engineering.get("testing_score", 0) or 0)
        metric_card("Testing", f"{testing_score:.1f}", "Test coverage signal", "Observed testing posture", "good" if testing_score >= 80 else "bad", "✓", progress=testing_score)
    with p4:
        documentation_score = float(engineering.get("documentation_score", 0) or 0)
        metric_card("Documentation", f"{documentation_score:.1f}", "Documentation signal", "README, license and contributor docs", "good" if documentation_score >= 80 else "bad", "▤", progress=documentation_score)
    st.caption(f"Last commit: {activity.get('last_commit_days_ago', 0)} days ago · {engineering.get('dependencies_observed', 0)} observed dependencies · {engineering.get('test_files', 0)} test files")

    c1, c2 = st.columns(2)
    with c1:
        section_header("Assessment", "A plain-language interpretation of the latest scan.")
        st.write(result["intro"])
        insight_card("Primary improvement area", f"{result['weakest_dimension']}. {result['priorities'][0]}", "warning", "Priority", "↳")
    with c2:
        section_header("Repository pulse", "The core numbers behind this scan.")
        r1, r2, r3 = st.columns(3)
        with r1:
            metric_card("Contributors", _fmt(metrics.get("total_contributors", 0)), help_text="Visible contributor volume", icon="◎")
        with r2:
            metric_card("Bus factor", _fmt(metrics.get("bus_factor", 0)), help_text="Contributor concentration signal", icon="⊙")
        with r3:
            metric_card("Recent commits", _fmt(metrics.get("recent_commit_count", 0)), help_text="Recent development activity", icon="↻")

    history_df = _history_frame(repo.full_name)
    _render_scorecard(analysis, history_df, risks, result)
    _render_resilience(analysis, history_df)
    if not history_df.empty:
        section_header("Repository timeline", "See how repository health and development momentum have evolved across every stored scan.", "Evolution intelligence")
        render_repository_health_timeline(history_df, height=430)
        _render_timeline_moments(history_df)

        section_header("Health trajectory", "A focused view of the health signal across stored scans.", "Historical telemetry")
        render_health_trajectory(history_df, height=300)
    _render_history(repo.full_name)
